### ISSUE TITLE
Missing use of open_form and close_form Twig abstractions

### ISSUE THREAD

**Issue by robotpony** [lemonstand/lscloud-theme-bones#22]
All forms are missing use of open_form / close_form twig functions

[Example from docs](https://docs.lemonstand.com/themes/search-page)

**Comment by rudy-sasquatchstudio** [comment]
Sorry @robotpony forgot to close this ticket.  Issue resolved in the following commit https://github.com/lemonstand/lscloud-theme-bones/commit/35b96bb64fd643606afbf8b048b948ad33637d01.  All html form tags converted to twig abstractions.
