### ISSUE TITLE
Dropping in to say

### ISSUE THREAD

**Issue by pixelota** [lemonstand/lscloud-theme-bones#24]
I'm pretty happy to see a lemonstand theme being developed using zurb foundation 6.xx. What is your timeline for releasing it?

**Comment by dhalarewich** [comment]
@pixelota We anticipate an initial beta release of bones v2 (what we're working on right now is the second version) in 2-3 weeks from now.

We will be using it to develop several premium themes which will put Bones through real world testing, using it as a base to build themes from. At that point we'll be able to remove the beta designation.
